### ISSUE TITLE
How to make outbound call ?

### ISSUE THREAD

**Issue by fadylateef** [plivo/plivo-ios-sdk2-examples#1]
When using the call view controller is just calls inbound , I need to make an outbound call !

**Comment by SivaPlivo** [comment]
@fadylateef Thank you for reaching out to us and your interest in Plivo iOS SDK. Please find below information about our call flow:

When you make calls using SIP Endpoint

1. The call will be redirected to Plivo (CallDirection set to inbound).
2. From Plivo, call will redirect to either GSM or SIP Endpoint(Outbound)

If you make calls using Plivo API

1. From Plivo call will redirect to either GSM or SIP Endpoint(Outbound)

![inbound](https://user-images.githubusercontent.com/26872159/34760767-18a26530-f607-11e7-87e0-94489452fdaa.png)

**Comment by fadylateef** [comment]
I am making calls from the app using my own username and password from my EndPoint which is for Demo Direct Call App , and it is only making inbound calls

**Comment by SivaPlivo** [comment]
Since you are making calls from endpoint... first it will redirect to Plivo(InBound) and then it will make an outbound call. So as per design direction of this call is inbound.

**Comment by fadylateef** [comment]
The app makes outbound calls only to my Sandbox Number.

**Comment by SivaPlivo** [comment]
If you log in and make calls using endpoint, it will always be an inbound call to Plivo(PF above screenshot). With our iOS SDK you cannot make direct outbound calls since you should login using Endpoint. 

If you want to make outbound calls you can use our API by passing auth_id, auth_token, from, to etc values. This API request will not redirect to Plivo and will fire call directly.

![screen shot 2018-01-10 at 3 10 16 pm](https://user-images.githubusercontent.com/26872159/34766496-a145a92a-f61a-11e7-8887-948e72188a19.jpg)

![screen shot 2018-01-10 at 3 10 54 pm 1](https://user-images.githubusercontent.com/26872159/34766687-377ef432-f61b-11e7-9c2c-9dbe585cf5f6.png)

For additional information please check the below link

https://www.plivo.com/docs/api/call/

**Comment by eniyavan-muruganantham-plivo** [comment]
@fadylateef 
If the issue persists please write to support@plivo.com.
